# Generated by Django 3.2.4 on 2021-06-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jassarten',
            name='eichle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jassarten',
            name='miser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jassarten',
            name='obeabe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jassarten',
            name='rose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jassarten',
            name='schilte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jassarten',
            name='schälle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jassarten',
            name='slalom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jassarten',
            name='uneufe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jassarten',
            name='wahl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jassarten',
            name='5/4',
            field=models.IntegerField(default=0),
        ),
    ]
