# Generated by Django 3.2.4 on 2021-06-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210625_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eichle_1', models.IntegerField(default=0)),
                ('eichle_2', models.IntegerField(default=0)),
                ('rose_1', models.IntegerField(default=0)),
                ('rose_2', models.IntegerField(default=0)),
                ('schilte_1', models.IntegerField(default=0)),
                ('schilte_2', models.IntegerField(default=0)),
                ('schälle_1', models.IntegerField(default=0)),
                ('schälle_2', models.IntegerField(default=0)),
                ('obeabe_1', models.IntegerField(default=0)),
                ('obeabe_2', models.IntegerField(default=0)),
                ('uneufe_1', models.IntegerField(default=0)),
                ('uneufe_2', models.IntegerField(default=0)),
                ('miser_1', models.IntegerField(default=0)),
                ('miser_2', models.IntegerField(default=0)),
                ('wahl_1', models.IntegerField(default=0)),
                ('wahl_2', models.IntegerField(default=0)),
                ('slalom_1', models.IntegerField(default=0)),
                ('slalom_2', models.IntegerField(default=0)),
                ('5/4_1', models.IntegerField(default=0)),
                ('5/4_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Jass_1',
        ),
        migrations.DeleteModel(
            name='Jass_2',
        ),
    ]
