# Generated by Django 3.2.4 on 2021-06-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210625_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jass',
            new_name='Jas',
        ),
    ]
