# Generated by Django 3.2.4 on 2021-06-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_jass_jas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jas',
            name='5/4_2',
        ),
        migrations.RemoveField(
            model_name='jas',
            name='eichle_2',
        ),
        migrations.RemoveField(
            model_name='jas',
            name='miser_2',
        ),
        migrations.RemoveField(
            model_name='jas',
            name='obeabe_2',
        ),
        migrations.RemoveField(
            model_name='jas',
            name='rose_2',
        ),
        migrations.RemoveField(
            model_name='jas',
            name='schilte_2',
        ),
        migrations.RemoveField(
            model_name='jas',
            name='schälle_2',
        ),
        migrations.RemoveField(
            model_name='jas',
            name='slalom_2',
        ),
        migrations.RemoveField(
            model_name='jas',
            name='uneufe_2',
        ),
        migrations.RemoveField(
            model_name='jas',
            name='wahl_2',
        ),
    ]
