# Generated by Django 3.2.4 on 2021-06-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20210626_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jas',
            old_name='5/4_1',
            new_name='5/4',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='eichle_1',
            new_name='eichle',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='miser_1',
            new_name='miser',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='obeabe_1',
            new_name='obeabe',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='rose_1',
            new_name='rose',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='schilte_1',
            new_name='schilte',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='schälle_1',
            new_name='schälle',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='slalom_1',
            new_name='slalom',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='uneufe_1',
            new_name='uneufe',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='wahl_1',
            new_name='wahl',
        ),
    ]
