# Generated by Django 3.2.4 on 2021-06-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20210626_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='jas',
            name='team_name',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
    ]
