# Generated by Django 3.2.4 on 2021-06-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_jas_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jas',
            name='team_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
