# Generated by Django 3.2.4 on 2021-06-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_jas_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jas',
            old_name='5/4',
            new_name='3/3',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='eichle',
            new_name='4/5',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='miser',
            new_name='?',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='obeabe',
            new_name='Ei',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='rose',
            new_name='MiOb',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='schilte',
            new_name='Ro',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='schälle',
            new_name='Ro12',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='slalom',
            new_name='Se',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='uneufe',
            new_name='Si',
        ),
        migrations.RenameField(
            model_name='jas',
            old_name='wahl',
            new_name='Sl',
        ),
        migrations.AddField(
            model_name='jas',
            name='Un',
            field=models.IntegerField(default=0),
        ),
    ]
