# Generated by Django 3.2.4 on 2021-06-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20210630_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jas',
            old_name='MiOb',
            new_name='Mi',
        ),
        migrations.AddField(
            model_name='jas',
            name='Ob',
            field=models.IntegerField(default=0),
        ),
    ]
