# Generated by Django 3.2.4 on 2021-06-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20210630_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jas',
            new_name='JassTeam',
        ),
    ]
