# Generated by Django 3.2.4 on 2021-07-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_rename_jas_jassteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jassteam',
            old_name='3/3',
            new_name='3_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='4/5',
            new_name='4_5',
        ),
    ]
