# Generated by Django 3.2.4 on 2021-07-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20210703_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jassteam',
            name='4_5',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='?',
        ),
        migrations.AddField(
            model_name='jassteam',
            name='wahl4_5',
            field=models.IntegerField(default=0),
        ),
    ]
