# Generated by Django 3.2.4 on 2021-07-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_auto_20210703_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jassteam',
            name='3_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='4_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='Ei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='Mi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='Ob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='Ro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='Ro12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='Se',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='Si',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='Sl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='Un',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='wahl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
