# Generated by Django 3.2.4 on 2021-07-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_auto_20210703_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='jassteam',
            name='3_3',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='4_5',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='Ei',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='Mi',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='Ob',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='Ro',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='Ro12',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='Se',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='Si',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='Sl',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='Un',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='team_name',
            field=models.CharField(default='e', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='jassteam',
            name='wahl',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
