# Generated by Django 3.2.4 on 2021-07-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_auto_20210703_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jassteam',
            name='qr',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='jassteam',
            name='team_name',
            field=models.CharField(max_length=20),
        ),
    ]
