# Generated by Django 3.2.4 on 2021-07-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_auto_20210703_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jassteam',
            name='3_3',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='4_5',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='Ei',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='Mi',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='Ob',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='Ro',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='Ro12',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='Se',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='Si',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='Sl',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='Un',
        ),
        migrations.RemoveField(
            model_name='jassteam',
            name='wahl',
        ),
    ]
