# Generated by Django 3.2.4 on 2021-07-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_auto_20210731_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jassteam',
            old_name='3_3',
            new_name='3_3 ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='3_31',
            new_name='3_3 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='3_32',
            new_name='3_3 2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='4_5',
            new_name='4_5 ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='4_51',
            new_name='4_5 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='4_52',
            new_name='4_5 2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ei',
            new_name='Ei ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ei1',
            new_name='Ei 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ei2',
            new_name='Ei 2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Mi',
            new_name='Mi ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Mi1',
            new_name='Mi 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Mi2',
            new_name='Mi 2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ob',
            new_name='Ob ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ob1',
            new_name='Ob 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ob2',
            new_name='Ob 2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro',
            new_name='Ro ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro1',
            new_name='Ro 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro12',
            new_name='Ro 2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro121',
            new_name='Ro12 ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro122',
            new_name='Ro12 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro2',
            new_name='Ro12 2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Se',
            new_name='Se ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Se1',
            new_name='Se 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Se2',
            new_name='Se 2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Si',
            new_name='Si ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Si1',
            new_name='Si 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Si2',
            new_name='Si 2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Sl',
            new_name='Sl ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Sl1',
            new_name='Sl 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Sl2',
            new_name='Sl 2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Un',
            new_name='Un ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Un1',
            new_name='Un 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Un2',
            new_name='Un 2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='wahl',
            new_name='wahl ',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='wahl1',
            new_name='wahl 1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='wahl2',
            new_name='wahl 2',
        ),
    ]
