# Generated by Django 3.2.4 on 2021-08-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_auto_20210731_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jassteam',
            old_name='3_3 ',
            new_name='3_3_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='3_3 1',
            new_name='3_3_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='3_3 2',
            new_name='3_3_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='4_5 ',
            new_name='4_5_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='4_5 1',
            new_name='4_5_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='4_5 2',
            new_name='4_5_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ei ',
            new_name='Ei_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ei 1',
            new_name='Ei_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ei 2',
            new_name='Ei_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Mi ',
            new_name='Mi_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Mi 1',
            new_name='Mi_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Mi 2',
            new_name='Mi_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ob ',
            new_name='Ob_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ob 1',
            new_name='Ob_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ob 2',
            new_name='Ob_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro ',
            new_name='Ro12_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro 1',
            new_name='Ro12_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro 2',
            new_name='Ro12_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro12 ',
            new_name='Ro_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro12 1',
            new_name='Ro_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Ro12 2',
            new_name='Ro_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Se ',
            new_name='Se_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Se 1',
            new_name='Se_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Se 2',
            new_name='Se_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Si ',
            new_name='Si_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Si 1',
            new_name='Si_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Si 2',
            new_name='Si_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Sl ',
            new_name='Sl_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Sl 1',
            new_name='Sl_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Sl 2',
            new_name='Sl_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Un ',
            new_name='Un_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Un 1',
            new_name='Un_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='Un 2',
            new_name='Un_3',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='wahl ',
            new_name='wahl_1',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='wahl 1',
            new_name='wahl_2',
        ),
        migrations.RenameField(
            model_name='jassteam',
            old_name='wahl 2',
            new_name='wahl_3',
        ),
    ]
